### ISSUE TITLE
Impossible de résoudre le nom 'lsc:serviceType' en un composant 'type definition'

### ISSUE THREAD

**Issue by Abdoulsore** [lsc-project/lsc-obm-plugin#4]
Hi,
I'm trying to debug an LSC issue, I found the issue but I don't know how to fix it.
The first time I launched the task I got this error:
 `sept. 18 10:29:27 - ERROR - org.lsc.exception.LscConfigurationException: Configuration exception: Unknown plugin implementation: org.lsc.plugins.connectors.obm.ObmGroupDstService`
So I downloaded the obm plugin (lsc-obm-plugin-1.4-distribution.jar) and I added it in the lib directory (/usr/lib/lsc).
But now when I launch the task I got the error:

```
sept. 18 10:55:31 - ERROR - Unable to load configuration (org.lsc.exception.LscConfigurationException: Configuration exception: src-resolve : Impossible de résoudre le nom 'lsc:serviceType' en un composant 'type definition'.)
org.lsc.exception.LscConfigurationException: Configuration exception: src-resolve : Impossible de résoudre le nom 'lsc:serviceType' en un composant 'type definition'.
	at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:157) ~[lsc-core-2.1.4.jar:na]
	at org.lsc.Configuration.setUp(Configuration.java:482) [lsc-core-2.1.4.jar:na]
	at org.lsc.Configuration.setUp(Configuration.java:456) [lsc-core-2.1.4.jar:na]
	at org.lsc.Launcher.run(Launcher.java:205) [lsc-core-2.1.4.jar:na]
	at org.lsc.Launcher.launch(Launcher.java:158) [lsc-core-2.1.4.jar:na]
	at org.lsc.Launcher.main(Launcher.java:141) [lsc-core-2.1.4.jar:na]
Caused by: org.xml.sax.SAXParseException: src-resolve : Impossible de résoudre le nom 'lsc:serviceType' en un composant 'type definition'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_161]
	....
```
Thanks for your help!

**Comment by rouazana** [comment]
The issue is probably related to Java 8. Can you please try with Java 7?

Anyway we must keep this issue open to make it work fine with Java 8.

**Comment by Abdoulsore** [comment]
Thank you, that was the problem. After switching to java 7 it works fine :)
thank you!
